import type { Metadata } from "next";
import { Inter, Figtree } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const figtree = Figtree({ subsets: ["latin"], weight: ["400", "500", "700"] });
export const metadata: Metadata = {
  title: "Adan Gordon - Full Stack NextJs Developer | New York, NY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${figtree.className}`}>
        {children}
      </body>
    </html>
  );
}
